### ISSUE TITLE
Crash on 1.12.2-1.0.5

### ISSUE THREAD

**Issue by hugoalh** [gigaherz/InventorySpam#7]
1.12.2-1.0.5 made the game crash when entering a world, 1.12.2-1.0.3 is fine.
```
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.FMLLaunchHandler.isDeobfuscatedEnvironment()Z
	at gigaherz.inventoryspam.ContainerWrapper.<clinit>(ContainerWrapper.java:23)
	at gigaherz.inventoryspam.ScrollingOverlay.clientTick(ScrollingOverlay.java:276)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1875_ScrollingOverlay_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1910)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gigaherz.inventoryspam.ContainerWrapper.<clinit>(ContainerWrapper.java:23)
	at gigaherz.inventoryspam.ScrollingOverlay.clientTick(ScrollingOverlay.java:276)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1875_ScrollingOverlay_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
```

**Comment by gigaherz** [comment]
Hey sorry I missed this issue, as I mentioned in #8, you need 2779 or newer, since I used a feature that didn't exist in older versions. I forgot to mark the release as needing this version or newer, in the mod's metadata.

**Comment by hugoalh** [comment]
Oh, because I use 2768...
Thanks for reply!
